server:
  port: 8080
  tomcat:
    max-threads: 10
spring:
  application:
    name: gateway-server

# 配置spring cloud gateway路由
  cloud:
    gateway:
      routes:
        # 配置路由：路由id，路由到微服务的uri，断言(判断条件)
        - id: product-service
          uri: http://localhost:9001
          predicates:
            - Path=/product/**

