#模拟两个eureka server
#端口9000，8000
#两个server需要相互注册


server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否将自己注册到注册中心
    fetch-registry: false #是否要从eureka中获取注册信息
    service-url: #配置暴露给Eureka Client的请求地址
      defalutZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false # 关闭自我保护机制
    eviction-interval-timer-in-ms: 4000 # 设置剔除服务间隔

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?userUnicode=true&characterEncoding=utf-8
    username: root
    password: liuhao123
  application:
    name: eureka-server
